"""
setup_env.py — interactively create the .env file the push scripts read.

    python3 scripts/setup_env.py

Prompts for each value, hides the API token as you type, writes .env at the repo
root with 0600 permissions, and (optionally) verifies the token against the live
Webflow API before finishing. Re-run any time to update values; existing values are
offered as defaults and you can press Enter to keep them.

Non-interactive alternative: skip this script entirely and set WEBFLOW_API_TOKEN etc.
as environment variables (see .env.example). wf_config.load_config() reads either.
"""

import json
import os
import ssl
import sys
import urllib.error
import urllib.request
from getpass import getpass

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from wf_config import KNOWN, parse_env_file  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_PATH = os.path.join(REPO_ROOT, ".env")

# (key, prompt, required, secret, default)
FIELDS = [
    ("WEBFLOW_API_TOKEN", "Webflow Data API token (input hidden)", True, True, ""),
    ("WEBFLOW_COLLECTION_ID", "Target CMS collection id", True, False, "67756fb6c22d9437aa3af048"),
    ("WEBFLOW_BODY_FIELD", "RichText field slug", False, False, "article-text"),
    ("WEBFLOW_SITE_ID", "Site id (optional, for publish/list)", False, False, ""),
    ("WEBFLOW_DB_PATH", "Absolute path to local SQLite DB (optional)", False, False, ""),
]


def mask(v):
    return ("*" * max(0, len(v) - 4)) + v[-4:] if v else "(unset)"


def verify_token(token, collection_id):
    """GET one item from the collection to confirm the token + collection work."""
    ctx = ssl.create_default_context()
    try:
        import certifi
        ctx = ssl.create_default_context(cafile=certifi.where())
    except ImportError:
        pass  # system certs; fine on Linux
    url = "https://api.webflow.com/v2/collections/%s/items?limit=1" % collection_id
    req = urllib.request.Request(
        url, headers={"Authorization": "Bearer %s" % token, "Accept": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, context=ctx, timeout=30) as resp:
            data = json.loads(resp.read().decode("utf-8"))
        total = data.get("pagination", {}).get("total", "?")
        return True, "OK — collection reachable, %s items total." % total
    except urllib.error.HTTPError as e:
        hint = {
            401: "token invalid or expired",
            403: "token lacks CMS scope for this site",
            404: "collection id not found for this token's site",
        }.get(e.code, "HTTP %s" % e.code)
        return False, "Failed: %s" % hint
    except Exception as e:  # network, TLS, etc.
        return False, "Could not reach Webflow: %s" % e


def main():
    print("=== Webflow CMS Ops — .env setup ===\n")
    existing = parse_env_file(ENV_PATH) if os.path.exists(ENV_PATH) else {}
    if existing:
        print("Found existing .env — current values shown as defaults.")
        print("(token: %s)\n" % mask(existing.get("WEBFLOW_API_TOKEN", "")))

    values = {}
    for key, prompt, required, secret, default in FIELDS:
        current = existing.get(key, default)
        while True:
            if secret:
                shown = mask(current) if current else "none"
                entry = getpass("%s [%s]: " % (prompt, shown))
                value = entry or current
            else:
                suffix = " [%s]" % current if current else ""
                entry = input("%s%s: " % (prompt, suffix)).strip()
                value = entry or current
            if required and not value:
                print("  → required, please enter a value.")
                continue
            break
        values[key] = value

    # Write .env (only keys we know about; skip empty optionals).
    lines = ["# Webflow CMS Ops — generated by scripts/setup_env.py", "# Do NOT commit this file.", ""]
    for key in KNOWN:
        if values.get(key):
            lines.append("%s=%s" % (key, values[key]))
    content = "\n".join(lines) + "\n"

    if os.path.exists(ENV_PATH):
        ans = input("\n.env already exists. Overwrite? [y/N]: ").strip().lower()
        if ans not in ("y", "yes"):
            print("Aborted. No changes written.")
            return 1

    with open(ENV_PATH, "w") as f:
        f.write(content)
    os.chmod(ENV_PATH, 0o600)
    print("\nWrote %s (permissions 600)." % ENV_PATH)

    # Confirm .env is gitignored so the token can't be committed by accident.
    gi = os.path.join(REPO_ROOT, ".gitignore")
    ignored = os.path.exists(gi) and any(
        l.strip() in (".env", "*.env", "/.env") for l in open(gi)
    )
    print("  .gitignore covers .env: %s" % ("yes" if ignored else "NO — add it!"))

    # Offer a live verification.
    ans = input("\nVerify the token against Webflow now? [Y/n]: ").strip().lower()
    if ans in ("", "y", "yes"):
        ok, msg = verify_token(values["WEBFLOW_API_TOKEN"], values["WEBFLOW_COLLECTION_ID"])
        print("  %s" % msg)
        if not ok:
            print("  Fix the value and re-run:  python3 scripts/setup_env.py")
            return 1

    print("\nDone. The push scripts will pick this up via wf_config.load_config().")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (KeyboardInterrupt, EOFError):
        print("\nAborted.")
        sys.exit(130)
